language: android
jdk: oraclejdk7
sudo: false
env:
  #matrix:
   # - ANDROID_TARGET=android-21  ANDROID_ABI=armeabi-v7a
  global:
      - ANDROID_BUILD_API_LEVEL=22
      - ANDROID_BUILD_TOOLS_VERSION=22.0.1
      - ANDROID_ABI=default/armeabi-v7a
      - ANDROID_EMULATOR_API_LEVEL=19
android:
  components:
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_BUILD_API_LEVEL
    - extra-google-google_play_services
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository

before_script:
  # Create and start emulator
  - sudo apt-get update -qq
  - sudo apt-get install -qq libstdc++6:i386 lib32z1 expect
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
 # - ./gradlew clean assembleDebug
  - ./gradlew build connectedCheck